version: '3.1'
services:
#  mongodb:
#    image: mongo:4.2
#    restart: always
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
  rabbitmq:
    image: circleci/rabbitmq-delayed:3.7.23-management-31
    ports:
      - "15672:15672"
      - "5672:5672"